Run peaceiris/actions-gh-pages@v3
[INFO] Usage https://github.com/peaceiris/actions-gh-pages#readme
Dump inputs
Setup auth token
Prepare publishing assets
Setup Git config
Create a commit
Push the commit or tag
  /usr/bin/git push origin gh-pages
  remote: Permission to flaviengibs/brevet-app-qcm.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/flaviengibs/brevet-app-qcm.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Token fourni automatiquement par GitHub pour l'authentification
        publish_dir: ./ # Le dossier à publier (ici, la racine du dépôt)
